name: bump

on:
  pull_request:
    types: [closed]
    branches: [dev]

jobs:
  bump:
    name: 'Bump version on _main_'
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'HOTFIX')}}
    run:
      echo Hello world!
      
